name: Deploy beruangan to VPS

# Robot jalan tiap kali kamu git push ke branch master
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Tarik kode terbaru dari repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js & Build Vue
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: Build Vue Frontend
        run: |
          cd fe-vue
          npm install
          npm run build

      # 3. Setup Golang & Build Single Binary
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go App
        run: |
          GOOS=linux GOARCH=amd64 go build -o beruangan-app .

      # 4. Kirim file biner ke VPS pakai SCP
      - name: Copy Binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "beruangan-app"
          target: "/home/magentaadam/projects/beruangan-app"

      # 5. Eksekusi restart/start menggunakan PM2 di VPS
      - name: Restart App in VPS with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Panggil NVM biar Node.js dan PM2 terdeteksi!
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Masuk ke folder project
            cd /home/magentaadam/projects/beruangan-app
            chmod +x beruangan-app
            
            # 3. Hajar pakai PM2 biasa (nggak perlu alamat panjang lagi)
            pm2 restart beruangan || pm2 start ./beruangan-app --name "beruangan"
            pm2 save