name: Deploy beruangan to VPS

# Robot jalan tiap kali kamu git push ke branch master
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Tarik kode terbaru dari repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js & Build Vue
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Vue Frontend
        run: |
          cd fe-vue
          npm install
          npm run build

      # 3. Setup Golang & Build Single Binary
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Go App
        run: |
          GOOS=linux GOARCH=amd64 go build -o beruangan-app .

      # 4. Kirim file biner ke VPS pakai SCP
      - name: Copy Binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }} # <--- Menggunakan SSH Key
          source: "beruangan-app"
          target: "/home/magentaadam/projects/beruangan-app"

      # 5. Eksekusi restart sistem di VPS
      - name: Restart App in VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }} # <--- Menggunakan SSH Key
          script: |
            cd /home/magentaadam/projects/beruangan-app
            chmod +x beruangan-app
            # Tambahan sudo karena user magentaadam butuh akses admin
            sudo systemctl restart beruangan.service
